apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
  labels:
    app: argo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
        - name: argo-app-container
          image: sha2121/argo-app:2
          ports:
            - containerPort: 3000
