apiVersion: v1
kind: Service
metadata:
  name: argo-app-service
  labels:
    app: argo-app
spec:
  selector:
    app: argo-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
